=== BackupTheBerlios/gpon/dev/ws/src/main/resources/wsdl/gponscript.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://berlios.de/gpon/xmlscript" targetNamespace="http://berlios.de/gpon/xmlscript" elementFormDefault="qualified">
	<!-- GponScript Document-->
	<xs:element name="GponScript">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Processing"/>
				<xs:choice maxOccurs="unbounded">
				    <xs:group ref="DmlLikeGroup"/>
					<xs:group ref="SetLikeGroup"/>
					<xs:group ref="AssociationLikeGroup"/>
					<!-- Delete, Update -->
					<xs:group ref="VoidGroup"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Processing -->
	<xs:element name="Processing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Commit"/>
				<xs:element ref="Results"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Commit">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="auto"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Results">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Smtp"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Smtp Address -->
	<xs:element name="Smtp" type="xs:string"/>
	
	<!--  DDL -->
	<xs:element name="CreateObjectType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DeclareProperty"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="description" type="xs:string"/>
			<xs:attribute name="baseType" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="DeclareProperty">
		<xs:complexType>
			<xs:attribute name="name"        type="xs:string"/>
			<xs:attribute name="description" type="xs:string"/>
			<xs:attribute name="type"        type="xs:string"/>
			<xs:attribute name="mandatory"   type="xs:boolean"/>
			<xs:attribute name="rank"        type="xs:integer"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="RemoveObjectType">
		<xs:complexType>
		  <xs:attribute name="name" type="xs:string"/>
	    </xs:complexType>
    </xs:element>
    
	<xs:element name="CreateAssociationType">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="description" type="xs:string"/>
			<xs:attribute name="multiplicity">
			 <xs:simpleType>
        	  <xs:restriction base="xs:NMTOKEN">
          		<xs:enumeration value="OneToOne"/>
          		<xs:enumeration value="OneToMany"/>
          		<xs:enumeration value="ManyToMany"/>
        	  </xs:restriction>
      		 </xs:simpleType>
            </xs:attribute>
			<xs:attribute name="visibility">
			 <xs:simpleType>
        	  <xs:restriction base="xs:NMTOKEN">
          		<xs:enumeration value="ab"/>
          		<xs:enumeration value="ba"/>
          		<xs:enumeration value="abba"/>
        	  </xs:restriction>
      		 </xs:simpleType>
            </xs:attribute>
   			<xs:attribute name="typeOfA" type="xs:string"/>
   			<xs:attribute name="roleOfA" type="xs:string"/>
   			<xs:attribute name="typeOfB" type="xs:string"/>
   			<xs:attribute name="roleOfB" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="RemoveAssociationType">
	  <xs:complexType>
			<xs:attribute name="name" type="xs:string"/>
	  </xs:complexType>
	</xs:element>
	
	<!--  DML constructs -->
	<xs:group name="DmlLikeGroup">
		<xs:choice>
			<xs:element ref="CreateObjectType"/>
			<xs:element ref="CreateAssociationType"/>
			<xs:element ref="RemoveObjectType"/>
			<xs:element ref="RemoveAssociationType"/>
		</xs:choice>
	</xs:group>
	
	<!--  Voids -->
	<xs:group name="VoidGroup">
		<xs:choice>
			<xs:element ref="Removal"/>
		</xs:choice>
	</xs:group>

    <!-- Removal -->
    <xs:element name="Removal">
      <xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
	  </xs:complexType>
    </xs:element>
	
	<!-- non visible abstraction of a set like construct -->
	<xs:group name="SetLikeGroup">
		<xs:choice>
			<!-- set operations -->
			<xs:element ref="Union"/>
			<xs:element ref="Intersection"/>
			<xs:element ref="Difference"/>
			<!-- objects -->
			<xs:element ref="Query"/>
			<xs:element ref="Creation"/>
			<xs:element ref="Update"/>
			<xs:element ref="Reference"/>
		</xs:choice>
	</xs:group>
	<xs:group name="AssociationLikeGroup">
		<xs:choice>
			<!-- associations  -->
			<xs:element ref="Associate"/>
			<xs:element ref="Dissociate"/>
		</xs:choice>
	</xs:group>
	<!-- Union -->
	<xs:element name="Union">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup" maxOccurs="50"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Intersection -->
	<xs:element name="Intersection">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup" maxOccurs="50"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Difference -->
	<xs:element name="Difference">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup" minOccurs="2" maxOccurs="2"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Set Reference -->
	<xs:element name="Reference">
		<xs:complexType>
			<xs:attribute name="refid">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<!-- Query -->
	<xs:element name="Query">
		<xs:complexType>
			<xs:group ref="AssociatedExpr" minOccurs="0"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="spec" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:group name="AssociatedExpr">
		<xs:choice>
			<xs:element ref="Associated"/>
			<xs:element ref="Or"/>
			<xs:element ref="Xor"/>
			<xs:element ref="And"/>
			<xs:element ref="Not"/>
		</xs:choice>
	</xs:group>
	<xs:element name="And">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="AssociatedExpr"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Associated">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="by" type="xs:string" use="required"/>
			<xs:attribute name="role" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Creation -->
	<xs:element name="Creation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="OrUpdateUsingKeys"/>
				<xs:element ref="CreateObject" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="when" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateObject">
		<xs:complexType>
			<xs:sequence>
				<!-- Properties -->
				<xs:element ref="Property" maxOccurs="unbounded"/>
				<!-- Associated Objects -->
				<xs:element ref="AssociateWith" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AssociateWith">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="role" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DissociateFrom">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="role" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- Update -->
	<xs:element name="Update">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="On"/>
				<xs:element ref="UpdateObject" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="UpdateObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Associate Sets -->
	<xs:element name="Associate">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup"/>
				<xs:element ref="AssociateWith"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Or">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="AssociatedExpr"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Xor">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="AssociatedExpr"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Not">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="AssociatedExpr" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dissociate">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="SetLikeGroup"/>
				<xs:element ref="DissociateFrom"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Key">
	 <xs:complexType>
	  <xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	</xs:element>
	<xs:element name="On">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Reference"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="OrUpdateUsingKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Key" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BackupTheBerlios/gpon/dev/script/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp1 U (http://www.altova.com) by Daniel Schulz (Family Works :)) -->
<GponScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="http://berlios.de/gpon/xmlscript"
            xsi:noNamespaceSchemaLocation="../xmlbeans/xsd/gponscript.xsd" >
	<Processing>
		<Commit>auto</Commit>
		<Results>
			<Smtp/>
		</Results>
	</Processing>
	<Difference id="diff_1">
		<Union id="union_1">
			<Query id="q1" type="server.unix" spec="${name} like '%'"/>
			<Query id="mounts" type="server.unix.mountpoint" spec="${host} &lt;&gt; 'yvis'"/>
		</Union>
		<Reference refid="ee"/>
	</Difference>
	<Query id="q1" type="server.unix" spec="${name} like '%'"/>
	<Query id="mounts" type="server.unix.mountpoint" spec="${host} &lt;&gt; 'yvis'"/>
	<Query id="all_mounts" type="server.unix.mountpoint"/>
	<Query type="server.unix" spec="tac_to_number(${cpu.count},'999999') &gt;= 2">
	 <Xor id="xor_1">
	  <Not id="not_1">
	  <Associated by="server.unix.mounted" role="Server">
	   <Query id="mounts" type="server.unix.mountpoint" spec="${host} &lt;&gt; 'yvis'"/>
	  </Associated>
	  </Not>
	  
	  <Associated by="server.unix.mounted" role="Server">
	   <Reference refid="all_mounts"/>
	  </Associated>
	  
	 </Xor>
	 
	</Query>
	<Creation id="new_server_list" type="ci.base">
	 <CreateObject>
	  <Property name="inventory.no" value="BLALABER"/>
	  <Property name="update.date" value="17.10.2004"/>
	  <AssociateWith role="bla">
	   <Creation type="ci.base" id="new_network_device_list">
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER1"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER2"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER3"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER4"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER5"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER6"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER7"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER8"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER9"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER10"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	    <CreateObject>
 	     <Property name="inventory.no" value="BLALABER11"/>
	     <Property name="update.date" value="17.10.2004"/>
	    </CreateObject>
	   </Creation>
	  </AssociateWith>
	 </CreateObject>
	</Creation>
</GponScript>

=== BackupTheBerlios/gpon/dev/script/CreateType.xml
<?xml version="1.0" encoding="UTF-8"?>
<GponScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="http://berlios.de/gpon/xmlscript"
            xsi:noNamespaceSchemaLocation="../xmlbeans/xsd/gponscript.xsd" >
	<Processing>
		<Commit>auto</Commit>
		<Results>
			<Smtp/>
		</Results>
	</Processing>
    <!-- -->
    <RemoveObjectType name="Car"/> 
    <RemoveObjectType name="Person"/> 
    <RemoveAssociationType name="driver"/>
    
    <CreateObjectType description="car" name="Car">
    	<DeclareProperty name="license.plate.no" description="Kennzeichen" mandatory="true" rank="1" type="ShortText"/>
    	<DeclareProperty name="chassis.no" description="Fahrgestellnummer" mandatory="true" rank="2" type="ShortText"/>
        <DeclareProperty name="yom" description="Year of Manufacture" mandatory="true" rank="3" type="DateType"/>
        <DeclareProperty name="color" description="Color" mandatory="false" rank="4" type="ShortText"/>
    </CreateObjectType>
    
    <CreateObjectType description="person" name="Person">
        <DeclareProperty name="name" description="Name" mandatory="true" rank="1" type="ShortText"/>
        <DeclareProperty name="firstname" description="Vorname" mandatory="true"  rank="2" type="ShortText"/>
        <DeclareProperty name="birthday" description="Birthday" mandatory="true"  rank="3" type="DateType"/>
    </CreateObjectType>
    
    <CreateAssociationType 
    	name="driver"
    	description="Driver"
    	multiplicity="ManyToMany"
    	roleOfA="driver"
    	typeOfA="Person"
    	roleOfB="car"
    	typeOfB="Car"
    	visibility="abba"
    />
</GponScript>

=== BackupTheBerlios/gpon/dev/script/OneToMany.xml
<?xml version="1.0" encoding="UTF-8"?>
<GponScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="http://berlios.de/gpon/xmlscript"
            xsi:noNamespaceSchemaLocation="../xml/xsd/gponscript.xsd" >
	<Processing>
		<Commit>auto</Commit>
		<Results>
			<Smtp/>
		</Results>
	</Processing>
   <CreateObjectType description="One" name="one">
        <DeclareProperty name="name" description="Name" mandatory="true" rank="1" type="ShortText"/>
    </CreateObjectType>
    
    <CreateObjectType description="Many" name="many">
        <DeclareProperty name="name" description="Name" mandatory="true" rank="1" type="ShortText"/>
    </CreateObjectType>
    <CreateAssociationType 
    	name="one-to-many"
    	description="One To Many"
    	multiplicity="OneToMany"
    	roleOfA="one"
    	typeOfA="one"
    	roleOfB="many"
    	typeOfB="many"
    	visibility="abba"
    />
	<Creation id="many" type="many">
	 <OrUpdateUsingKeys>
	  <Key name="name"/>
	 </OrUpdateUsingKeys>
	 <CreateObject>
	  <Property name="name"      value="m1"/>
	 </CreateObject>
	 <CreateObject> 
	  <Property name="name"      value="m2"/>
	 </CreateObject>
	 <CreateObject> 
	  <Property name="name"      value="m3"/>
	 </CreateObject>
	</Creation>

	<Creation id="one" type="one">
	 <OrUpdateUsingKeys>
	  <Key name="name"/>
	 </OrUpdateUsingKeys>
	 <CreateObject>
        <Property name="name" value="o1"/>
	    <AssociateWith type="one-to-many" role="one">
		 <Reference refid="many"/>
	    </AssociateWith>
	 </CreateObject>
	</Creation>
	
	<Query id="manies" type="many">
	 <Associated by="one-to-many" role="many"/>
	</Query>
</GponScript>

=== BackupTheBerlios/gpon/dev/script/CreateDriversAndCars.xml
<?xml version="1.0" encoding="UTF-8"?>
<GponScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="http://berlios.de/gpon/xmlscript"
            xsi:noNamespaceSchemaLocation="../xml/xsd/gponscript.xsd" >
	<Processing>
		<Commit>auto</Commit>
		<Results>
			<Smtp/>
		</Results>
	</Processing>
	<!--  
	<Removal>
	  <Union>
	   <Query type="Person"/>
	   <Query type="Car"/>
	  </Union>
	</Removal>
    -->
	<Creation id="HellDrivers" type="Person">
	 <OrUpdateUsingKeys>
	  <Key name="name"/>
	  <Key name="firstname"/>
	 </OrUpdateUsingKeys>
	 <CreateObject>
	  <Property name="name"      value="Schulz"/>
	  <Property name="firstname" value="Daniel"/>
	  <Property name="birthday"  value="1.2.1974"/>
	 </CreateObject>
	 <CreateObject> 
	  <Property name="name"      value="Schulz"/>
	  <Property name="firstname" value="Claire (Schatzi)"/>
	  <Property name="birthday"  value="30.5.1973 8:52:15"/>
	 </CreateObject>
	 <CreateObject> 
	  <Property name="name"      value="Schulz"/>
	  <Property name="firstname" value="Claire"/>
	  <Property name="birthday"  value="30.5.1973 8:52:15"/>
	 </CreateObject>
	</Creation>

    <!-- this car is associated with 2 drivers -->	

	<Creation id="OneCar" type="Car">
	 <OrUpdateUsingKeys>
	  <Key name="license.plate.no"/>
	 </OrUpdateUsingKeys>
	 <CreateObject>
	    <Property name="license.plate.no" value="LOS-LJ 256"/>
    	<Property name="chassis.no" value="TMBXY1234567890"/>
        <Property name="yom" value="1.10.2005"/>
        <Property name="color" value="black"/>
	    <AssociateWith type="driver" role="car">
		 <Reference refid="HellDrivers"/>
	    </AssociateWith>
	 </CreateObject>
	</Creation>
	
	<Query id="PersonsThatAreDrivers" type="Person">
	 <Associated by="driver" role="driver"/>
	</Query>
	
	<Query id="PersonsThatAreDrivers2" type="Person">
	 <Associated by="driver" role="driver">
	  <Query id="AllCars" type="Car"/>
	 </Associated>
	</Query>
</GponScript>
